/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Doc Flow API
 * OpenAPI spec version: v1
 */
import { axiosInstance } from './axios-instance';
export interface ChangePasswordDTO {
	currentPassword: string;
	newPassword: string;
}

export interface DocumentCreateDTO {
	name: string;
	/** @nullable */
	categoryId: number | null;
	isPrivate: boolean;
}

export interface DocumentGeneralInfoDTO {
	id: number;
	name: string;
	/** @nullable */
	authorId: number | null;
	/** @nullable */
	categoryId: number | null;
	isPrivate: boolean;
}

export interface DocumentVersionGeneralInfoDTO {
	id: number;
	version: number;
}

export interface DocumentDraftDTO {
	content: string;
	modifiedAt: string;
}

export interface DocumentDTO {
	generalInfo: DocumentGeneralInfoDTO;
	versions: DocumentVersionGeneralInfoDTO[];
	draft: DocumentDraftDTO;
	canEdit: boolean;
}

export interface DocumentVersionDTO {
	id: number;
	version: number;
	content: string;
}

export interface DocumentWithVersionDTO {
	generalInfo: DocumentGeneralInfoDTO;
	version: DocumentVersionDTO;
	canEdit: boolean;
}

export interface UserDTO {
	id: number;
	name: string;
	surname: string;
	email: string;
}

export interface UserLoginDTO {
	email: string;
	password: string;
}

export interface UserRegistrateDTO {
	name: string;
	surname: string;
	email: string;
	password: string;
}

export const getDocFlowAPI = () => {
	const registerUser = (
		userRegistrateDTO?: UserRegistrateDTO,
	) => {
		return axiosInstance<string>(
			{
				url: `/api/Account/register`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: userRegistrateDTO
			},
		);
	}

	const loginUser = (
		userLoginDTO?: UserLoginDTO,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Account/login`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: userLoginDTO
			},
		);
	}

	const changeUserPassword = (
		changePasswordDTO?: ChangePasswordDTO,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Account/change-password`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: changePasswordDTO
			},
		);
	}

	const deleteUserAccount = (

	) => {
		return axiosInstance<void>(
			{
				url: `/api/Account`, method: 'DELETE'
			},
		);
	}

	const getDocumentById = (
		id: number,
	) => {
		return axiosInstance<DocumentDTO>(
			{
				url: `/api/Documents/${id}`, method: 'GET'
			},
		);
	}

	const getDocumentVersion = (
		documentId: number,
		versionId: number,
	) => {
		return axiosInstance<DocumentWithVersionDTO>(
			{
				url: `/api/Documents/${documentId}/versions/${versionId}`, method: 'GET'
			},
		);
	}

	const deleteDocumentVersion = (
		documentId: number,
		versionId: number,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${documentId}/versions/${versionId}`, method: 'DELETE'
			},
		);
	}

	const createDocument = (
		documentCreateDTO?: DocumentCreateDTO,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: documentCreateDTO
			},
		);
	}

	const updateDocumentGeneralInfo = (
		id: number,
		documentGeneralInfoDTO?: DocumentGeneralInfoDTO,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${id}/general-info`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: documentGeneralInfoDTO
			},
		);
	}

	const createDraftFromVersion = (
		id: number,
		createDraftFromVersionBody?: number,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${id}/draft`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: createDraftFromVersionBody
			},
		);
	}

	const saveDocumentDraft = (
		id: number,
		saveDocumentDraftBody?: string,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${id}/draft/save`, method: 'POST',
				headers: { 'Content-Type': 'application/json', },
				data: saveDocumentDraftBody
			},
		);
	}

	const resetDocumentDraft = (
		id: number,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${id}/draft/reset`, method: 'POST'
			},
		);
	}

	const addDocumentVersion = (
		id: number,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${id}/versions`, method: 'POST'
			},
		);
	}

	const deleteDocument = (
		documentId: number,
	) => {
		return axiosInstance<void>(
			{
				url: `/api/Documents/${documentId}`, method: 'DELETE'
			},
		);
	}

	const getUserById = (
		id: number,
	) => {
		return axiosInstance<UserDTO>(
			{
				url: `/api/Users/${id}`, method: 'GET'
			},
		);
	}

	const getUserDocuments = (
		id: number,
	) => {
		return axiosInstance<DocumentDTO[]>(
			{
				url: `/api/Users/${id}/documents`, method: 'GET'
			},
		);
	}

	return { registerUser, loginUser, changeUserPassword, deleteUserAccount, getDocumentById, getDocumentVersion, deleteDocumentVersion, createDocument, updateDocumentGeneralInfo, createDraftFromVersion, saveDocumentDraft, resetDocumentDraft, addDocumentVersion, deleteDocument, getUserById, getUserDocuments }
};
export type RegisterUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['registerUser']>>>
export type LoginUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['loginUser']>>>
export type ChangeUserPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['changeUserPassword']>>>
export type DeleteUserAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['deleteUserAccount']>>>
export type GetDocumentByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['getDocumentById']>>>
export type GetDocumentVersionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['getDocumentVersion']>>>
export type DeleteDocumentVersionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['deleteDocumentVersion']>>>
export type CreateDocumentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['createDocument']>>>
export type UpdateDocumentGeneralInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['updateDocumentGeneralInfo']>>>
export type CreateDraftFromVersionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['createDraftFromVersion']>>>
export type SaveDocumentDraftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['saveDocumentDraft']>>>
export type ResetDocumentDraftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['resetDocumentDraft']>>>
export type AddDocumentVersionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['addDocumentVersion']>>>
export type DeleteDocumentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['deleteDocument']>>>
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['getUserById']>>>
export type GetUserDocumentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDocFlowAPI>['getUserDocuments']>>>
